export const initialRoster = {
    url: "google.com",
    players: {
        "Bill": {
            G: "18",
            PER: "10.2",
            "TS%": ".406",
            WS: "0.5",
            P_G: "25",
            P_PER: "8.2",
            "P_TS%": ".545",
            P_WS: "0.7"
        }
    }
};

export const initialSchedule = {
    url: "google.com",
    games : {
        "1": {
            "Date": "Tue, Oct 27, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200910270LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Los Angeles Clippers",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "92",
            "W": "1",
            "L": "0",
            "Streak": "W 1"
        },
        "2": {
            "Date": "Fri, Oct 30, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200910300LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Dallas Mavericks",
            "Result": "L",
            "PtsFor": "80",
            "PtsOpp": "94",
            "W": "1",
            "L": "1",
            "Streak": "L 1"
        },
        "3": {
            "Date": "Sun, Nov 1, 2009",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911010LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Atlanta Hawks",
            "Result": "W",
            "PtsFor": "118",
            "PtsOpp": "110",
            "W": "2",
            "L": "1",
            "Streak": "W 1"
        },
        "4": {
            "Date": "Tue, Nov 3, 2009",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911030OKC.html",
            "Location": "Oklahoma City Thunder",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "101",
            "PtsOpp": "98",
            "W": "3",
            "L": "1",
            "Streak": "W 2"
        },
        "5": {
            "Date": "Wed, Nov 4, 2009",
            "Start (ET)": "8:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911040HOU.html",
            "Location": "Houston Rockets",
            "Opponent": "Houston Rockets",
            "Result": "W",
            "PtsFor": "103",
            "PtsOpp": "102",
            "W": "4",
            "L": "1",
            "Streak": "W 3"
        },
        "6": {
            "Date": "Fri, Nov 6, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911060LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Memphis Grizzlies",
            "Result": "W",
            "PtsFor": "114",
            "PtsOpp": "98",
            "W": "5",
            "L": "1",
            "Streak": "W 4"
        },
        "7": {
            "Date": "Sun, Nov 8, 2009",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911080LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "New Orleans Hornets",
            "Result": "W",
            "PtsFor": "104",
            "PtsOpp": "88",
            "W": "6",
            "L": "1",
            "Streak": "W 5"
        },
        "8": {
            "Date": "Thu, Nov 12, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911120LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "121",
            "PtsOpp": "102",
            "W": "7",
            "L": "1",
            "Streak": "W 6"
        },
        "9": {
            "Date": "Fri, Nov 13, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911130DEN.html",
            "Location": "Denver Nuggets",
            "Opponent": "Denver Nuggets",
            "Result": "L",
            "PtsFor": "79",
            "PtsOpp": "105",
            "W": "7",
            "L": "2",
            "Streak": "L 1"
        },
        "10": {
            "Date": "Sun, Nov 15, 2009",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911150LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Houston Rockets",
            "Result": "L",
            "PtsFor": "91",
            "PtsOpp": "101",
            "W": "7",
            "L": "3",
            "Streak": "L 2"
        },
        "11": {
            "Date": "Tue, Nov 17, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911170LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Detroit Pistons",
            "Result": "W",
            "PtsFor": "106",
            "PtsOpp": "93",
            "W": "8",
            "L": "3",
            "Streak": "W 1"
        },
        "12": {
            "Date": "Thu, Nov 19, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911190LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Chicago Bulls",
            "Result": "W",
            "PtsFor": "108",
            "PtsOpp": "93",
            "W": "9",
            "L": "3",
            "Streak": "W 2"
        },
        "13": {
            "Date": "Sun, Nov 22, 2009",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911220LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "101",
            "PtsOpp": "85",
            "W": "10",
            "L": "3",
            "Streak": "W 3"
        },
        "14": {
            "Date": "Tue, Nov 24, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911240LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "New York Knicks",
            "Result": "W",
            "PtsFor": "100",
            "PtsOpp": "90",
            "W": "11",
            "L": "3",
            "Streak": "W 4"
        },
        "15": {
            "Date": "Sat, Nov 28, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911280GSW.html",
            "Location": "Golden State Warriors",
            "Opponent": "Golden State Warriors",
            "Result": "W",
            "PtsFor": "130",
            "PtsOpp": "97",
            "W": "12",
            "L": "3",
            "Streak": "W 5"
        },
        "16": {
            "Date": "Sun, Nov 29, 2009",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200911290LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "New Jersey Nets",
            "Result": "W",
            "PtsFor": "106",
            "PtsOpp": "87",
            "W": "13",
            "L": "3",
            "Streak": "W 6"
        },
        "17": {
            "Date": "Tue, Dec 1, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912010LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "New Orleans Hornets",
            "Result": "W",
            "PtsFor": "110",
            "PtsOpp": "99",
            "W": "14",
            "L": "3",
            "Streak": "W 7"
        },
        "18": {
            "Date": "Fri, Dec 4, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912040LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Miami Heat",
            "Result": "W",
            "PtsFor": "108",
            "PtsOpp": "107",
            "W": "15",
            "L": "3",
            "Streak": "W 8"
        },
        "19": {
            "Date": "Sun, Dec 6, 2009",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912060LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "108",
            "PtsOpp": "88",
            "W": "16",
            "L": "3",
            "Streak": "W 9"
        },
        "20": {
            "Date": "Wed, Dec 9, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912090LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "101",
            "PtsOpp": "77",
            "W": "17",
            "L": "3",
            "Streak": "W 10"
        },
        "21": {
            "Date": "Fri, Dec 11, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912110LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Minnesota Timberwolves",
            "Result": "W",
            "PtsFor": "104",
            "PtsOpp": "92",
            "W": "18",
            "L": "3",
            "Streak": "W 11"
        },
        "22": {
            "Date": "Sat, Dec 12, 2009",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912120UTA.html",
            "Location": "Utah Jazz",
            "Opponent": "Utah Jazz",
            "Result": "L",
            "PtsFor": "94",
            "PtsOpp": "102",
            "W": "18",
            "L": "4",
            "Streak": "L 1"
        },
        "23": {
            "Date": "Tue, Dec 15, 2009",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912150CHI.html",
            "Location": "Chicago Bulls",
            "Opponent": "Chicago Bulls",
            "Result": "W",
            "PtsFor": "96",
            "PtsOpp": "87",
            "W": "19",
            "L": "4",
            "Streak": "W 1"
        },
        "24": {
            "Date": "Wed, Dec 16, 2009",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912160MIL.html",
            "Location": "Milwaukee Bucks",
            "Opponent": "Milwaukee Bucks",
            "Result": "W",
            "PtsFor": "107",
            "PtsOpp": "106",
            "W": "20",
            "L": "4",
            "Streak": "W 2"
        },
        "25": {
            "Date": "Sat, Dec 19, 2009",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912190NJN.html",
            "Location": "New Jersey Nets",
            "Opponent": "New Jersey Nets",
            "Result": "W",
            "PtsFor": "103",
            "PtsOpp": "84",
            "W": "21",
            "L": "4",
            "Streak": "W 3"
        },
        "26": {
            "Date": "Sun, Dec 20, 2009",
            "Start (ET)": "6:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912200DET.html",
            "Location": "Detroit Pistons",
            "Opponent": "Detroit Pistons",
            "Result": "W",
            "PtsFor": "93",
            "PtsOpp": "81",
            "W": "22",
            "L": "4",
            "Streak": "W 4"
        },
        "27": {
            "Date": "Tue, Dec 22, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912220LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "111",
            "PtsOpp": "108",
            "W": "23",
            "L": "4",
            "Streak": "W 5"
        },
        "28": {
            "Date": "Fri, Dec 25, 2009",
            "Start (ET)": "5:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912250LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Cleveland Cavaliers",
            "Result": "L",
            "PtsFor": "87",
            "PtsOpp": "102",
            "W": "23",
            "L": "5",
            "Streak": "L 1"
        },
        "29": {
            "Date": "Sat, Dec 26, 2009",
            "Start (ET)": "10:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912260SAC.html",
            "Location": "Sacramento Kings",
            "Opponent": "Sacramento Kings",
            "Result": "W",
            "PtsFor": "112",
            "PtsOpp": "103",
            "W": "24",
            "L": "5",
            "Streak": "W 1"
        },
        "30": {
            "Date": "Mon, Dec 28, 2009",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912280PHO.html",
            "Location": "Phoenix Suns",
            "Opponent": "Phoenix Suns",
            "Result": "L",
            "PtsFor": "103",
            "PtsOpp": "118",
            "W": "24",
            "L": "6",
            "Streak": "L 1"
        },
        "31": {
            "Date": "Tue, Dec 29, 2009",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/200912290LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Golden State Warriors",
            "Result": "W",
            "PtsFor": "124",
            "PtsOpp": "118",
            "W": "25",
            "L": "6",
            "Streak": "W 1"
        },
        "32": {
            "Date": "Fri, Jan 1, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001010LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Sacramento Kings",
            "Result": "W",
            "PtsFor": "109",
            "PtsOpp": "108",
            "W": "26",
            "L": "6",
            "Streak": "W 2"
        },
        "33": {
            "Date": "Sun, Jan 3, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001030LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Dallas Mavericks",
            "Result": "W",
            "PtsFor": "131",
            "PtsOpp": "96",
            "W": "27",
            "L": "6",
            "Streak": "W 3"
        },
        "34": {
            "Date": "Tue, Jan 5, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001050LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Houston Rockets",
            "Result": "W",
            "PtsFor": "88",
            "PtsOpp": "79",
            "W": "28",
            "L": "6",
            "Streak": "W 4"
        },
        "35": {
            "Date": "Wed, Jan 6, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001060LAC.html",
            "Location": "Los Angeles Clippers",
            "Opponent": "Los Angeles Clippers",
            "Result": "L",
            "PtsFor": "91",
            "PtsOpp": "102",
            "W": "28",
            "L": "7",
            "Streak": "L 1"
        },
        "36": {
            "Date": "Fri, Jan 8, 2010",
            "Start (ET)": "10:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001080POR.html",
            "Location": "Portland Trail Blazers",
            "Opponent": "Portland Trail Blazers",
            "Result": "L",
            "PtsFor": "98",
            "PtsOpp": "107",
            "W": "28",
            "L": "8",
            "Streak": "L 2"
        },
        "37": {
            "Date": "Sun, Jan 10, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001100LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Milwaukee Bucks",
            "Result": "W",
            "PtsFor": "95",
            "PtsOpp": "77",
            "W": "29",
            "L": "8",
            "Streak": "W 1"
        },
        "38": {
            "Date": "Tue, Jan 12, 2010",
            "Start (ET)": "8:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001120SAS.html",
            "Location": "San Antonio Spurs",
            "Opponent": "San Antonio Spurs",
            "Result": "L",
            "PtsFor": "85",
            "PtsOpp": "105",
            "W": "29",
            "L": "9",
            "Streak": "L 1"
        },
        "39": {
            "Date": "Wed, Jan 13, 2010",
            "Start (ET)": "8:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001130DAL.html",
            "Location": "Dallas Mavericks",
            "Opponent": "Dallas Mavericks",
            "Result": "W",
            "PtsFor": "100",
            "PtsOpp": "95",
            "W": "30",
            "L": "9",
            "Streak": "W 1"
        },
        "40": {
            "Date": "Fri, Jan 15, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001150LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Los Angeles Clippers",
            "Result": "W",
            "PtsFor": "126",
            "PtsOpp": "86",
            "W": "31",
            "L": "9",
            "Streak": "W 2"
        },
        "41": {
            "Date": "Mon, Jan 18, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001180LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Orlando Magic",
            "Result": "W",
            "PtsFor": "98",
            "PtsOpp": "92",
            "W": "32",
            "L": "9",
            "Streak": "W 3"
        },
        "42": {
            "Date": "Thu, Jan 21, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001210CLE.html",
            "Location": "Cleveland Cavaliers",
            "Opponent": "Cleveland Cavaliers",
            "Result": "L",
            "PtsFor": "87",
            "PtsOpp": "93",
            "W": "32",
            "L": "10",
            "Streak": "L 1"
        },
        "43": {
            "Date": "Fri, Jan 22, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001220NYK.html",
            "Location": "New York Knicks",
            "Opponent": "New York Knicks",
            "Result": "W",
            "PtsFor": "115",
            "PtsOpp": "105",
            "W": "33",
            "L": "10",
            "Streak": "W 1"
        },
        "44": {
            "Date": "Sun, Jan 24, 2010",
            "Start (ET)": "6:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001240TOR.html",
            "Location": "Toronto Raptors",
            "Opponent": "Toronto Raptors",
            "Result": "L",
            "PtsFor": "105",
            "PtsOpp": "106",
            "W": "33",
            "L": "11",
            "Streak": "L 1"
        },
        "45": {
            "Date": "Tue, Jan 26, 2010",
            "Start (ET)": "7:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001260WAS.html",
            "Location": "Washington Wizards",
            "Opponent": "Washington Wizards",
            "Result": "W",
            "PtsFor": "115",
            "PtsOpp": "103",
            "W": "34",
            "L": "11",
            "Streak": "W 1"
        },
        "46": {
            "Date": "Wed, Jan 27, 2010",
            "Start (ET)": "7:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001270IND.html",
            "Location": "Indiana Pacers",
            "Opponent": "Indiana Pacers",
            "Result": "W",
            "PtsFor": "118",
            "PtsOpp": "96",
            "W": "35",
            "L": "11",
            "Streak": "W 2"
        },
        "47": {
            "Date": "Fri, Jan 29, 2010",
            "Start (ET)": "7:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001290PHI.html",
            "Location": "Philadelphia 76ers",
            "Opponent": "Philadelphia 76ers",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "91",
            "W": "36",
            "L": "11",
            "Streak": "W 3"
        },
        "48": {
            "Date": "Sun, Jan 31, 2010",
            "Start (ET)": "3:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201001310BOS.html",
            "Location": "Boston Celtics",
            "Opponent": "Boston Celtics",
            "Result": "W",
            "PtsFor": "90",
            "PtsOpp": "89",
            "W": "37",
            "L": "11",
            "Streak": "W 4"
        },
        "49": {
            "Date": "Mon, Feb 1, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002010MEM.html",
            "Location": "Memphis Grizzlies",
            "Opponent": "Memphis Grizzlies",
            "Result": "L",
            "PtsFor": "93",
            "PtsOpp": "95",
            "W": "37",
            "L": "12",
            "Streak": "L 1"
        },
        "50": {
            "Date": "Wed, Feb 3, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002030LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Charlotte Bobcats",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "97",
            "W": "38",
            "L": "12",
            "Streak": "W 1"
        },
        "51": {
            "Date": "Fri, Feb 5, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002050LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Denver Nuggets",
            "Result": "L",
            "PtsFor": "113",
            "PtsOpp": "126",
            "W": "38",
            "L": "13",
            "Streak": "L 1"
        },
        "52": {
            "Date": "Sat, Feb 6, 2010",
            "Start (ET)": "10:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002060POR.html",
            "Location": "Portland Trail Blazers",
            "Opponent": "Portland Trail Blazers",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "82",
            "W": "39",
            "L": "13",
            "Streak": "W 1"
        },
        "53": {
            "Date": "Mon, Feb 8, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002080LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "San Antonio Spurs",
            "Result": "W",
            "PtsFor": "101",
            "PtsOpp": "89",
            "W": "40",
            "L": "13",
            "Streak": "W 2"
        },
        "54": {
            "Date": "Wed, Feb 10, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002100UTA.html",
            "Location": "Utah Jazz",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "96",
            "PtsOpp": "81",
            "W": "41",
            "L": "13",
            "Streak": "W 3"
        },
        "55": {
            "Date": "Tue, Feb 16, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002160LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Golden State Warriors",
            "Result": "W",
            "PtsFor": "104",
            "PtsOpp": "94",
            "W": "42",
            "L": "13",
            "Streak": "W 4"
        },
        "56": {
            "Date": "Thu, Feb 18, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002180LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Boston Celtics",
            "Result": "L",
            "PtsFor": "86",
            "PtsOpp": "87",
            "W": "42",
            "L": "14",
            "Streak": "L 1"
        },
        "57": {
            "Date": "Tue, Feb 23, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002230MEM.html",
            "Location": "Memphis Grizzlies",
            "Opponent": "Memphis Grizzlies",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "98",
            "W": "43",
            "L": "14",
            "Streak": "W 1"
        },
        "58": {
            "Date": "Wed, Feb 24, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002240DAL.html",
            "Location": "Dallas Mavericks",
            "Opponent": "Dallas Mavericks",
            "Result": "L",
            "PtsFor": "96",
            "PtsOpp": "101",
            "W": "43",
            "L": "15",
            "Streak": "L 1"
        },
        "59": {
            "Date": "Fri, Feb 26, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002260LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Philadelphia 76ers",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "90",
            "W": "44",
            "L": "15",
            "Streak": "W 1"
        },
        "60": {
            "Date": "Sun, Feb 28, 2010",
            "Start (ET)": "3:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201002280LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Denver Nuggets",
            "Result": "W",
            "PtsFor": "95",
            "PtsOpp": "89",
            "W": "45",
            "L": "15",
            "Streak": "W 2"
        },
        "61": {
            "Date": "Tue, Mar 2, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003020LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Indiana Pacers",
            "Result": "W",
            "PtsFor": "122",
            "PtsOpp": "99",
            "W": "46",
            "L": "15",
            "Streak": "W 3"
        },
        "62": {
            "Date": "Thu, Mar 4, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003040MIA.html",
            "Location": "Miami Heat",
            "Opponent": "Miami Heat",
            "Result": "L",
            "PtsFor": "111",
            "PtsOpp": "114",
            "W": "46",
            "L": "16",
            "Streak": "L 1"
        },
        "63": {
            "Date": "Fri, Mar 5, 2010",
            "Start (ET)": "7:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003050CHA.html",
            "Location": "Charlotte Bobcats",
            "Opponent": "Charlotte Bobcats",
            "Result": "L",
            "PtsFor": "83",
            "PtsOpp": "98",
            "W": "46",
            "L": "17",
            "Streak": "L 2"
        },
        "64": {
            "Date": "Sun, Mar 7, 2010",
            "Start (ET)": "2:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003070ORL.html",
            "Location": "Orlando Magic",
            "Opponent": "Orlando Magic",
            "Result": "L",
            "PtsFor": "94",
            "PtsOpp": "96",
            "W": "46",
            "L": "18",
            "Streak": "L 3"
        },
        "65": {
            "Date": "Tue, Mar 9, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003090LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Toronto Raptors",
            "Result": "W",
            "PtsFor": "109",
            "PtsOpp": "107",
            "W": "47",
            "L": "18",
            "Streak": "W 1"
        },
        "66": {
            "Date": "Fri, Mar 12, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003120PHO.html",
            "Location": "Phoenix Suns",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "102",
            "PtsOpp": "96",
            "W": "48",
            "L": "18",
            "Streak": "W 2"
        },
        "67": {
            "Date": "Mon, Mar 15, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003150GSW.html",
            "Location": "Golden State Warriors",
            "Opponent": "Golden State Warriors",
            "Result": "W",
            "PtsFor": "124",
            "PtsOpp": "121",
            "W": "49",
            "L": "18",
            "Streak": "W 3"
        },
        "68": {
            "Date": "Tue, Mar 16, 2010",
            "Start (ET)": "10:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003160SAC.html",
            "Location": "Sacramento Kings",
            "Opponent": "Sacramento Kings",
            "Result": "W",
            "PtsFor": "106",
            "PtsOpp": "99",
            "W": "50",
            "L": "18",
            "Streak": "W 4"
        },
        "69": {
            "Date": "Fri, Mar 19, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003190LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Minnesota Timberwolves",
            "Result": "W",
            "PtsFor": "104",
            "PtsOpp": "96",
            "W": "51",
            "L": "18",
            "Streak": "W 5"
        },
        "70": {
            "Date": "Sun, Mar 21, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003210LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Washington Wizards",
            "Result": "W",
            "PtsFor": "99",
            "PtsOpp": "92",
            "W": "52",
            "L": "18",
            "Streak": "W 6"
        },
        "71": {
            "Date": "Wed, Mar 24, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003240SAS.html",
            "Location": "San Antonio Spurs",
            "Opponent": "San Antonio Spurs",
            "Result": "W",
            "PtsFor": "92",
            "PtsOpp": "83",
            "W": "53",
            "L": "18",
            "Streak": "W 7"
        },
        "72": {
            "Date": "Fri, Mar 26, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003260OKC.html",
            "Location": "Oklahoma City Thunder",
            "Opponent": "Oklahoma City Thunder",
            "Result": "L",
            "PtsFor": "75",
            "PtsOpp": "91",
            "W": "53",
            "L": "19",
            "Streak": "L 1"
        },
        "73": {
            "Date": "Sat, Mar 27, 2010",
            "Start (ET)": "8:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003270HOU.html",
            "Location": "Houston Rockets",
            "Opponent": "Houston Rockets",
            "Result": "W",
            "PtsFor": "109",
            "PtsOpp": "101",
            "W": "54",
            "L": "19",
            "Streak": "W 1"
        },
        "74": {
            "Date": "Mon, Mar 29, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003290NOH.html",
            "Location": "New Orleans Hornets",
            "Opponent": "New Orleans Hornets",
            "Result": "L",
            "PtsFor": "100",
            "PtsOpp": "108",
            "W": "54",
            "L": "20",
            "Streak": "L 1"
        },
        "75": {
            "Date": "Wed, Mar 31, 2010",
            "Start (ET)": "7:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201003310ATL.html",
            "Location": "Atlanta Hawks",
            "Opponent": "Atlanta Hawks",
            "Result": "L",
            "PtsFor": "92",
            "PtsOpp": "109",
            "W": "54",
            "L": "21",
            "Streak": "L 2"
        },
        "76": {
            "Date": "Fri, Apr 2, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004020LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "106",
            "PtsOpp": "92",
            "W": "55",
            "L": "21",
            "Streak": "W 1"
        },
        "77": {
            "Date": "Sun, Apr 4, 2010",
            "Start (ET)": "3:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004040LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "San Antonio Spurs",
            "Result": "L",
            "PtsFor": "81",
            "PtsOpp": "100",
            "W": "55",
            "L": "22",
            "Streak": "L 1"
        },
        "78": {
            "Date": "Thu, Apr 8, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004080DEN.html",
            "Location": "Denver Nuggets",
            "Opponent": "Denver Nuggets",
            "Result": "L",
            "PtsFor": "96",
            "PtsOpp": "98",
            "W": "55",
            "L": "23",
            "Streak": "L 2"
        },
        "79": {
            "Date": "Fri, Apr 9, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004090MIN.html",
            "Location": "Minnesota Timberwolves",
            "Opponent": "Minnesota Timberwolves",
            "Result": "W",
            "PtsFor": "97",
            "PtsOpp": "88",
            "W": "56",
            "L": "23",
            "Streak": "W 1"
        },
        "80": {
            "Date": "Sun, Apr 11, 2010",
            "Start (ET)": "3:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004110LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Portland Trail Blazers",
            "Result": "L",
            "PtsFor": "88",
            "PtsOpp": "91",
            "W": "56",
            "L": "24",
            "Streak": "L 1"
        },
        "81": {
            "Date": "Tue, Apr 13, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004130LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Sacramento Kings",
            "Result": "W",
            "PtsFor": "106",
            "PtsOpp": "100",
            "W": "57",
            "L": "24",
            "Streak": "W 1"
        },
        "82": {
            "Date": "Wed, Apr 14, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004140LAC.html",
            "Location": "Los Angeles Clippers",
            "Opponent": "Los Angeles Clippers",
            "Result": "L",
            "PtsFor": "91",
            "PtsOpp": "107",
            "W": "57",
            "L": "25",
            "Streak": "L 1"
        },
        "P_1": {
            "Date": "Sun, Apr 18, 2010",
            "Start (ET)": "3:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004180LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "87",
            "PtsOpp": "79",
            "W": "1",
            "L": "0",
            "Streak": "W 1"
        },
        "P_2": {
            "Date": "Tue, Apr 20, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004200LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "95",
            "PtsOpp": "92",
            "W": "2",
            "L": "0",
            "Streak": "W 2"
        },
        "P_3": {
            "Date": "Thu, Apr 22, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004220OKC.html",
            "Location": "Oklahoma City Thunder",
            "Opponent": "Oklahoma City Thunder",
            "Result": "L",
            "PtsFor": "96",
            "PtsOpp": "101",
            "W": "2",
            "L": "1",
            "Streak": "L 1"
        },
        "P_4": {
            "Date": "Sat, Apr 24, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004240OKC.html",
            "Location": "Oklahoma City Thunder",
            "Opponent": "Oklahoma City Thunder",
            "Result": "L",
            "PtsFor": "89",
            "PtsOpp": "110",
            "W": "2",
            "L": "2",
            "Streak": "L 2"
        },
        "P_5": {
            "Date": "Tue, Apr 27, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004270LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "111",
            "PtsOpp": "87",
            "W": "3",
            "L": "2",
            "Streak": "W 1"
        },
        "P_6": {
            "Date": "Fri, Apr 30, 2010",
            "Start (ET)": "9:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201004300OKC.html",
            "Location": "Oklahoma City Thunder",
            "Opponent": "Oklahoma City Thunder",
            "Result": "W",
            "PtsFor": "95",
            "PtsOpp": "94",
            "W": "4",
            "L": "2",
            "Streak": "W 2"
        },
        "P_7": {
            "Date": "Sun, May 2, 2010",
            "Start (ET)": "3:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005020LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "104",
            "PtsOpp": "99",
            "W": "5",
            "L": "2",
            "Streak": "W 3"
        },
        "P_8": {
            "Date": "Tue, May 4, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005040LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "111",
            "PtsOpp": "103",
            "W": "6",
            "L": "2",
            "Streak": "W 4"
        },
        "P_9": {
            "Date": "Sat, May 8, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005080UTA.html",
            "Location": "Utah Jazz",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "111",
            "PtsOpp": "110",
            "W": "7",
            "L": "2",
            "Streak": "W 5"
        },
        "P_10": {
            "Date": "Mon, May 10, 2010",
            "Start (ET)": "10:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005100UTA.html",
            "Location": "Utah Jazz",
            "Opponent": "Utah Jazz",
            "Result": "W",
            "PtsFor": "111",
            "PtsOpp": "96",
            "W": "8",
            "L": "2",
            "Streak": "W 6"
        },
        "P_11": {
            "Date": "Mon, May 17, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005170LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "128",
            "PtsOpp": "107",
            "W": "9",
            "L": "2",
            "Streak": "W 7"
        },
        "P_12": {
            "Date": "Wed, May 19, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005190LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "124",
            "PtsOpp": "112",
            "W": "10",
            "L": "2",
            "Streak": "W 8"
        },
        "P_13": {
            "Date": "Sun, May 23, 2010",
            "Start (ET)": "8:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005230PHO.html",
            "Location": "Phoenix Suns",
            "Opponent": "Phoenix Suns",
            "Result": "L",
            "PtsFor": "109",
            "PtsOpp": "118",
            "W": "10",
            "L": "3",
            "Streak": "L 1"
        },
        "P_14": {
            "Date": "Tue, May 25, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005250PHO.html",
            "Location": "Phoenix Suns",
            "Opponent": "Phoenix Suns",
            "Result": "L",
            "PtsFor": "106",
            "PtsOpp": "115",
            "W": "10",
            "L": "4",
            "Streak": "L 2"
        },
        "P_15": {
            "Date": "Thu, May 27, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005270LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "103",
            "PtsOpp": "101",
            "W": "11",
            "L": "4",
            "Streak": "W 1"
        },
        "P_16": {
            "Date": "Sat, May 29, 2010",
            "Start (ET)": "8:30p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201005290PHO.html",
            "Location": "Phoenix Suns",
            "Opponent": "Phoenix Suns",
            "Result": "W",
            "PtsFor": "111",
            "PtsOpp": "103",
            "W": "12",
            "L": "4",
            "Streak": "W 2"
        },
        "P_17": {
            "Date": "Thu, Jun 3, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006030LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Boston Celtics",
            "Result": "W",
            "PtsFor": "102",
            "PtsOpp": "89",
            "W": "13",
            "L": "4",
            "Streak": "W 3"
        },
        "P_18": {
            "Date": "Sun, Jun 6, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006060LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Boston Celtics",
            "Result": "L",
            "PtsFor": "94",
            "PtsOpp": "103",
            "W": "13",
            "L": "5",
            "Streak": "L 1"
        },
        "P_19": {
            "Date": "Tue, Jun 8, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006080BOS.html",
            "Location": "Boston Celtics",
            "Opponent": "Boston Celtics",
            "Result": "W",
            "PtsFor": "91",
            "PtsOpp": "84",
            "W": "14",
            "L": "5",
            "Streak": "W 1"
        },
        "P_20": {
            "Date": "Thu, Jun 10, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006100BOS.html",
            "Location": "Boston Celtics",
            "Opponent": "Boston Celtics",
            "Result": "L",
            "PtsFor": "89",
            "PtsOpp": "96",
            "W": "14",
            "L": "6",
            "Streak": "L 1"
        },
        "P_21": {
            "Date": "Sun, Jun 13, 2010",
            "Start (ET)": "8:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006130BOS.html",
            "Location": "Boston Celtics",
            "Opponent": "Boston Celtics",
            "Result": "L",
            "PtsFor": "86",
            "PtsOpp": "92",
            "W": "14",
            "L": "7",
            "Streak": "L 2"
        },
        "P_22": {
            "Date": "Tue, Jun 15, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006150LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Boston Celtics",
            "Result": "W",
            "PtsFor": "89",
            "PtsOpp": "67",
            "W": "15",
            "L": "7",
            "Streak": "W 1"
        },
        "P_23": {
            "Date": "Thu, Jun 17, 2010",
            "Start (ET)": "9:00p",
            "Box Score": "https://www.basketball-reference.com//boxscores/201006170LAL.html",
            "Location": "LOS ANGELES LAKERS",
            "Opponent": "Boston Celtics",
            "Result": "W",
            "PtsFor": "83",
            "PtsOpp": "79",
            "W": "16",
            "L": "7",
            "Streak": "W 2"
        }
    }
};
