import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FooterLinks } from "../components/FooterLinks";
import MainMenu from "../components/MainMenu";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
    return (
        <div className={styles.container} id="mainPage">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           
            <main className={styles.main}>
                <div className={styles.menuHeader}>
                    <MainMenu menuType="top-menu"/>
                </div>
                <h1>
                    {"Hi I'm "}<a href="https://nextjs.org">Srinath Venkatesh</a>
                </h1>
            </main>

            <footer className={styles.footer}>
                <span>
                    <FooterLinks />
                </span>
            </footer>
        </div>
    );
};

export default Home;
